spring:
  application:
    name: application-service
    config:
      import: "optional:configserver:http://localhost:8088"
    id: application-service # Adding a unique identifier for the API
  mail:
    host: smtp.gmail.com
    port: 587
    username: kamdem.guy@institutsaintjean.org
    password: osurrusawvgooxam
    properties:
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

  datasource:
    url: jdbc:mysql://bi9vtsduv4xwtvolexl9-mysql.services.clever-cloud.com:3306/bi9vtsduv4xwtvolexl9?createDatabaseIfNotExist=true
    username: ugjnowpw0ykf96mt
    password: fEtV2YFx0FEWab0spfcN
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
